 export const surpriseMePrompts = [
  " Naruto Uzumaki: Using Shadow Clone Jutsu",
  " Sasuke Uchiha: Activating Sharingan",
  " Sakura Haruno: Healing a wounded ally",
  " Kakashi Hatake: Reading his favorite book",
  " Itachi Uchiha: Unveiling Mangekyou Sharingan",
  " Jiraiya: Summoning Gamabunta",
  " Tsunade: Displaying incredible strength",
  " Gaara: Controlling sand with his chakra",
  " Shikamaru Nara: Strategizing a battle plan",
  " Hinata Hyuga: Byakugan activated, blushing",
  " Rock Lee: Practicing intense martial arts",
  " Neji Hyuga: Gentle Fist fighting style",
  " Ino Yamanaka: Using Mind Transfer Jutsu",
  " Kiba Inuzuka: With his loyal dog, Akamaru",
  " Choji Akimichi: Eating a massive meal",
  " Temari: Summoning fierce wind gusts",
  " Shino Aburame: Surrounded by insects",
  " Sai: Showcasing artistic skills",
  " Yamato: Controlling wood-based techniques",
  " Orochimaru: Transforming into a snake-like form",
  " Goku (Dragon Ball Z): Powering up in Super Saiyan form",
  " Luffy (One Piece): Stretching his rubbery limbs",
  " Ichigo Kurosaki (Bleach): Wielding a massive Zanpakuto",
  " Sailor Moon (Sailor Moon): Posing with her Moon Wand",
  " Light Yagami (Death Note): Writing in the Death Note",
  " Eren Yeager (Attack on Titan): Maneuvering with 3D Maneuver Gear",
  " Edward Elric (Fullmetal Alchemist): Performing alchemy",
  " Gon Freecss (Hunter x Hunter): Fishing with a fishing rod",
  " Yu Yu Hakusho: Yusuke Urameshi using Spirit Gun",
  " Kenshin Himura (Rurouni Kenshin): Drawing his reverse-blade sword",
  " Natsu Dragneel (Fairy Tail): Breathing fire with Dragon Slayer Magic",
  " Gon and Killua (Hunter x Hunter): Training together",
  " Gintoki Sakata (Gintama): Sipping tea in his traditional attire",
  " Seiya (Saint Seiya): Wearing his Pegasus Bronze Cloth",
  " Kirito (Sword Art Online): Dual-wielding swords in Aincrad",
  " Rin Okumura (Blue Exorcist): Exorcising demons with a sword",
  " Sailor Mercury (Sailor Moon): Analyzing with her mini-computer",
  " Levi Ackerman (Attack on Titan): Cleaning with extreme precision",
  " L (Death Note): Sitting hunched over, deep in thought",
  " Kagome Higurashi (Inuyasha): Holding her Sacred Bow and arrows",
  
  " Rukia Kuchiki (Bleach): Gently smiling, wielding a katana",
  " Vegeta (Dragon Ball Z): Cross-armed, wearing Saiyan armor",
  " Lelouch Lamperouge (Code Geass): Commanding with Geass in his eye",
  " Saitama (One Punch Man): Unleashing a casual, yet devastating punch",
  " Alucard (Hellsing): Surrounded by shadows, releasing his powers",
  " Guts (Berserk): Clashing swords with his massive Dragon Slayer",
  " Gon and Killua (Hunter x Hunter): Celebrating a victory together",
  " Yugi Moto (Yu-Gi-Oh!): Summoning Dark Magician with Duel Disk",
  " Misato Katsuragi (Neon Genesis Evangelion): Sipping a cold beer",
  " Motoko Kusanagi (Ghost in the Shell): In cyberspace, connecting to the net",
  " Nausicaä (Nausicaä of the Valley of the Wind): Riding on her glider",
  " Ryuk (Death Note): Grinning mischievously while holding an apple",
  " Roy Mustang (Fullmetal Alchemist): Snapping fingers to create flames",
  " Rei Ayanami (Neon Genesis Evangelion): Standing still with an enigmatic expression",
  " Yoko Littner (Gurren Lagann): Holding her massive sniper rifle",
   "Yoko's Rifle, Vash the Stampede (Trigun): Flashing his signature peace sign",
   " Edward and Alphonse Elric (Fullmetal Alchemist): Researching alchemy in a library",
   " Roronoa Zoro (One Piece): Training with multiple swords",
   " Asuna Yuuki (Sword Art Online): Ready to engage in virtual combat",
   " Simon and Kamina (Gurren Lagann): Shouting Who the hell do you think I am?!",
  " Eren Yeager (Attack on Titan): Roaring in his Titan form",
  " Soma Yukihira (Food Wars!): Cooking up an exquisite dish",
  " C.C. (Code Geass): Sipping a cup of tea, wearing a mysterious smile",
  "Koro-sensei (Assassination Classroom): Grinning with tentacles extended",
  " Gon Freecss (Hunter x Hunter): Joyfully fishing with a bamboo pole",
  " Shoyo Hinata (Haikyuu!!): Spiking the ball with fierce determination",
  " Yugi Moto (Yu-Gi-Oh!): Summoning Exodia, the Forbidden One",
  " Mikasa Ackerman (Attack on Titan): Wielding her vertical maneuvering equipment",
  " Jotaro Kujo (JoJo's Bizarre Adventure): Stoic and posing in his signature style",
  " Monkey D. Luffy (One Piece): Flashing a carefree grin, ready for adventure",
  ];




